feat (social login): initial development for native social login
ForgeRock/forgerock-javascript-sdk pull request #104
Opened 2021-02-04 00:31 UTC by cerebrl

This is just a WIP PR for initial development of the social login feature. E2E automation and code refinement will follow soon.

2021-02-24 20:59 UTC, cerebrl commented on CHANGELOG.md
> +- New `FRAuth.start` method that aliases `FRAuth.next` to align native mobile SDKs
I just added this method to align with native mobile SDKs.

2021-02-24 21:00 UTC, cerebrl commented on src/fr-auth/index.ts
> +  public static async start(
This newly added method for SDK alignment is just essentially an alias to `FRAuth.next` in order to align with native mobile.

2021-02-25 16:55 UTC, spetrov requested changes
I tested manually social login with google and facebook with trees which use AM and IDM nodes and did some error case testing (mostly focusing on the FRAuth.redirect(step) and FRAuth.resume(url, options) methods to ensure that step information is properly stored and extracted from local storage (and then removed from there...)

There are 2 minor "test naming" mistakes that I've noticed. 
Other than that everything looks good to me! 👍

2021-02-25 16:55 UTC, spetrov commented on tests/e2e/suites/authn-social-login-am.test.ts
> +describe('Test bad login flow', () => {
This looks like a successful login flow?

2021-02-25 16:55 UTC, spetrov commented on tests/e2e/suites/authn-social-login-am.test.ts
> +    it(`Login with device profile callback ${browserType}`, async (done) => {
Social login with AM nodes?

2021-02-25 16:55 UTC, spetrov commented on tests/e2e/suites/authn-social-login-idm.test.ts
> +describe('Test bad login flow', () => {
Same here...

2021-02-25 16:55 UTC, spetrov commented on tests/e2e/suites/authn-social-login-idm.test.ts
> +    it(`Login with device profile callback ${browserType}`, async (done) => {
Successful social login with IDM nodes?

2021-02-25 22:40 UTC, cerebrl commented
@spetrov PR has been updated from your feedback. Thanks for catching the test naming.

2021-02-26 00:44 UTC, spetrov approved these changes
Looks good to me! 👍

2021-02-26 17:56 UTC, merged