sdks 1715/native saml support
ForgeRock/forgerock-javascript-sdk pull request #214
Opened 2022-04-28 03:11 UTC by ryanbas21

- feat(redirect): add SML related params to resume method
- test(autoscript-apps,autoscript-suites,mock-api): test-saml-support

# JIRA Ticket

https://bugster.forgerock.org/jira/browse/SDKS-1715

# Description

adds e2e test cases for saml support

# Type of Change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

e2e tests

# Definition of Done

Check all that apply

- [x] Acceptance criteria is met.
- [x] All tasks listed in the user story have been completed.
- [x] Coded to standards.
- [x] Code peer-reviewed.
- [x] Ensure backward compatibility (special attention).
- [x] API reference docs is updated.
- [x] Unit tests are written.
- [x] Integration tests are written.
- [x] e2e tests are written.
- [x] CI build passing on the feature branch.
- [x] Functional spec is written/updated
- [x] contains example code snippets.
- [x] Change log updated.
- [x] Documentation story is created and tracked.
- [x] UI is completed or ticket is created.
- [] Demo to PO and team.
- [x] Tech debts and remaining tasks are tracked in separated ticket(s).

## Documentation

- [ ] Acceptance criteria met
- [ ] Spell-check run
- [ ] Peer reviewed
- [ ] Proofread

2022-04-28 21:10 UTC, cerebrl requested changes
This looks like a good start, but here are some things I think are missing:

- Where in the server or the test suite are we "testing" if the SDK properly build the request? By that I mean the query parameters as well as the POST body.
- Please add the image of the tree used in the test. I know this is somewhat controversial, but let's stay consistent with what we do until we decide to alter it.
- Let's discuss the idea of also grabbing the `authIndexValue` for calling the right tree
- Can we also test to make sure the persisted state is removed after the resume is called?

2022-04-28 21:10 UTC, cerebrl commented on packages/javascript-sdk/src/fr-auth/index.ts
>      const parsedUrl = new URL(url);
I'm starting to think we could really help with grabbing the `authIndexValue` and pass that into our tree config in the options object when we call next.

2022-04-29 21:01 UTC, ryanbas21 commented on e2e/autoscript-apps/src/authn-saml/autoscript.ts
> +      });
No, it was just from copy pasting the social-login test and using that to build this. Fixing.

2022-04-29 21:10 UTC, ryanbas21 commented on e2e/mock-api/src/app/routes.auth.js
> +        res.json(authSuccess);
Yeah, i think this is a mistake.

2022-05-03 21:35 UTC, cerebrl approved these changes

2022-05-04 16:03 UTC, cerebrl approved these changes

2022-05-04 16:09 UTC, merged